### ISSUE TITLE
Implement IGD

### ISSUE THREAD

**Issue by nleroy917** [databio/gtars#28]
We need to re-implement IGD in this crate. Being done by @donaldcampbelljr in #9 

Original code here: https://github.com/databio/IGD

**Comment by donaldcampbelljr** [comment]
IGD create and search now work in PR #9 with some caveats.

An IGD database can be created from a folder full of bedfiles. A search can be performed using a single bed file as the query.

Performance-wise, creation appears to be similar for C and Rust versions (80 files, ~280,000 regions) at 2.1 seconds.

There are some discrepancies between the C version that should be investigated in the future such as:
- during searching, the number of counts may be off for one or more of the bedfiles. Most are the same, however. This may be due to pulling the `.igd` data back into memory for query. The gData tiles are not 1 to 1 (see attached picture). The _creation_ step appears to be exactly the same based on numbers (e.g. # of Ctgs, Regions, Tiles, etc).
- Certain bedfiles may cause the C version to crash but will pass using the Rust version and vice versa. Anecdotally, the Rust version appears to be more robust.
- Test performance for larger sets of bedfiles.
 
![image](https://github.com/user-attachments/assets/c0cd2edf-594e-445d-9167-aad4e1fcedd3)

**Comment by donaldcampbelljr** [comment]
I just merged the PR that has been in progress since beginning of the year. However, IGD still needs some work. 
- [ ] feature parity with C version
- [ ] understand any discrepancies between this version and C version
- [ ] python bindings were not yet implemented
